# _________________________________________________________________________
# ___ DEMO AND TESTING PURPOSES GET REQUESTS (To be Removed on Release) ___
# _________________________________________________________________________

# POST 'http://localhost:8000/recommend?page=1&limit=10'

### To build the skilltree, WARNING: THIS WILL TAKE HOURS, DON'T USE IT IF YOU HAVE AN EXISTING SKILLTREE
# GET http://localhost:8000/initializeSkillTree

### To build the skilltree from rawdata, then build the skills list from the skilltree - TAKES A MINUTE
GET http://localhost:8000/buildSkills


### Crawl into discovered links to generate new learning resources and filter DiscoveredLinks.json based on if the content exists in the skills list or not
GET http://localhost:8000/createLearningResoruces

###
GET http://localhost:8000/deleteBlockedLinks